### ISSUE TITLE
Check tenant exist

### ISSUE THREAD

**Issue by VjDharnish** [weaviate/weaviate-python-client#1011]
### Describe your feature request

Hello weaviate  , Checking a collection is existed or not is a good one. Why don't you add a particular tenant is present or not in a collection ?

### Code of Conduct

- [X] I have read and agree to the Weaviate's [Contributor Guide](https://weaviate.io/developers/contributor-guide) and [Code of Conduct](https://weaviate.io/service/code-of-conduct)

**Comment by dirkkul** [comment]
will be in the next python client release
