### ISSUE TITLE
Importing weaviate triggers `ResourceWarning: unclosed transport _SelectorSocketTransport`

### ISSUE THREAD

**Issue by knkski** [weaviate/weaviate-python-client#1080]
See here for context: https://github.com/langchain-ai/langchain/discussions/18293

Basically, running `import weaviate`, even without actually using the client, triggers some odd behavior with asyncio that looks like this:

```py
/home/zz/Programs/miniconda3/lib/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=19 read=idle write=<idle, bufsize=0>>
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

This is with weaviate 3.26.2. Unfortunately I can't upgrade beyond that due to the `llama-index-readers-weaviate` package [not supporting newer versions](https://github.com/run-llama/llama_index/blob/dbcc622a18f3d36bed09f48436710fad25fd510c/llama-index-integrations/readers/llama-index-readers-weaviate/pyproject.toml#L36).

**Comment by dirkkul** [comment]
Hey there,

v3 is deprecated and we won't fix issues like this anymore. 

WIll close this, please just open a new issue if you can reproduce in v4 and we will have a look
