### ISSUE TITLE
add Backup cancellation from client 

### ISSUE THREAD

**Issue by moogacs** [weaviate/weaviate-python-client#1252]
there are situations were backup gets stuck and in those situations we would like to cancel the created (stuck) backups. 

so Weaviate will support backup cancellation from `1.27+` and in order for clients users to be able to cancel  backups

[that is the new specification for deleting a backup ](https://github.com/weaviate/weaviate/pull/5639/files#diff-6e46d1a078f97315e53e6f21a97a0d18ac955212f3272ad75cfe0db74a248398R4862)

<img width="1075" alt="Screenshot 2024-08-22 at 16 41 26" src="https://github.com/user-attachments/assets/72d93173-6bfb-4205-8e09-ec22087a9057">

**Comment by moogacs** [comment]
linked issues : 
https://github.com/weaviate/java-client/issues/297
https://github.com/weaviate/weaviate-go-client/issues/240
https://github.com/weaviate/typescript-client/issues/188

**Comment by dirkkul** [comment]
this is merged
