### ISSUE TITLE
Collection.get() doesn't take a tenant?

### ISSUE THREAD

**Issue by awhillas** [weaviate/weaviate-python-client#1254]
I can't find _any examples_ of how you do multitenancy stuff with this API? 
[Here]( https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/collections/collections/sync.py#L167) you have .get() which initialises a Collection but you don't pass the tenant argument?!
There is _no_ documentation around tenants. How is one supposed to use it?

**Comment by dirkkul** [comment]
please use our [forum for support request](https://forum.weaviate.io/), thanks!

**Comment by tsmith023** [comment]
@awhillas, [here](https://weaviate.io/developers/weaviate/manage-data/multi-tenancy#crud-operations) are the docs for multi-tenancy CRUD ops
