### ISSUE TITLE
Update warning message for `datetime` use without timezone when querying

### ISSUE THREAD

**Issue by databyjp** [weaviate/weaviate-python-client#1265]
Queries show the same `datetime` warning as insertion, which can be confusing at first

```shell
Con002: You are inserting the datetime object 2017-01-01 00:00:00 without a timezone. The timezone will be set to UTC.
            To use a different timezone, specify it in the datetime object. For example:
            datetime.datetime(2021, 1, 1, 0, 0, 0, tzinfo=datetime.timezone(-datetime.timedelta(hours=2))).isoformat() = 2021-01-01T00:00:00-02:00
```

Proposal: could update `inserting` to `using` so it applies to both insertions & queries

**Comment by databyjp** [comment]
Hi @gssakash - Yup the proposal is for a text update of the existing error msg :) 

I do not think adding a second message would be necessary.

**Comment by gssakash** [comment]
I have generated a PR fixing this at #1320! I appreciate the prompt replies, thanks!
