### ISSUE TITLE
GraphQL Multiple queries and aliases support

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate-python-client#216]
Current Weavaite supports multiple queries and also [aliases]( https://graphql.org/learn/queries/#aliases) with multiple requests as below:

```graphql
{
  Get {
      one: Test {
        name
      }
      two: Test {
        name
      }
  }
}

{
  Get {
      Article {
        name
      }
      Paragraph {
        text
      }
  }
}
```

Would be great if the python client could support these features.

**Comment by Sasmuin** [comment]
I will try this.

**Comment by Sasmuin** [comment]
I have some questions regarding the implementation. My current idea was to implement it like this:
result = client.data_object.get(class_name=[Article","Person"])
result["Article"] and result["Person"] would then be the objects in that class. Is that how you imagined it?

**Comment by trengrj** [comment]
Hi @Sasmuin,

I was thinking about something like this. A new function `client.query.multi_get` that takes as inputs an array of unexecuted `get` queries and a `with_alias` property to add an alias.


For Example:

```python

client.query.multi_get([
    client.query.get("Test", ["name"]).with_alias("one"),
    client.query.get("Test", ["name"]).with_alias("one"),
    client.query.get("Article", ["paragraph"]),
]).do()

# or alternatively
with client.query as query:
    query.multi_get([
        query.get("Test", ["name", "description"]).with_alias("one"),
        query.get("Test", ["name", "description"]).with_alias("one")
        query.get("Article", ["paragraph"]),
    ]).do()
 ```
 
 Becomes
 
 ```graphql
{
  Get {
      one: Test {
        name
      }
      two: Test {
        name
      }
      Article {
        paragraph
      }
  }
}
```

@StefanBogdan do you have any thoughts on this?

**Comment by StefanBogdan** [comment]
I like the proposal from @trengrj! I think it should work.
