### ISSUE TITLE
Add docs for connection weaviate-client to official docker 

### ISSUE THREAD

**Issue by thirtyninetythree** [weaviate/weaviate-python-client#231]
In the docs, only 
```client = weaviate.Client("http://localhost:8080")``` is referenced in creating a weaviate client using docker. But you'll run into errors because you haven't configured the `WeaviateDocumentStore()`host (in haystack)

**Comment by dirkkul** [comment]
Hi, this repository is only for the weavaite python client. 

Your issue sounds like you haven't configured haystack so I think you should ask them or check their documentation. Also maybe @hsm207

**Comment by dirkkul** [comment]
Seems already be solved in our [slack](https://weaviate.slack.com/archives/C017EG2SL3H/p1676874149193119?thread_ts=1676757681.156399&cid=C017EG2SL3H)
