### ISSUE TITLE
Add method to check if a class exists

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate-python-client#232]
Add a function that returns if a given class exists in the schema

Proposal signature:
`client.schema.exists(className: str) ->bool`

**Comment by hsm207** [comment]
Closed by #311

**Comment by ashokrajab** [comment]
Do we have an equivant method to check whether a class exists in v4?

**Comment by hsm207** [comment]
> Do we have an equivant method to check whether a class exists in v4?

yes. it is:

```
client.collections.exists
```
