### ISSUE TITLE
support MacOS as platform for embedded DB

### ISSUE THREAD

**Issue by samos123** [weaviate/weaviate-python-client#239]

**Comment by dirkkul** [comment]
We started the process, but it will take a while

**Comment by c1scott** [comment]
would it be possible to also consider supporting WindowsOS as a platform for embedded DB?

**Comment by Jymany** [comment]
Windows EmbeddedDB please lord

**Comment by dirkkul** [comment]
Just to give more background:
Weaviate does not currently compile on windows and we cannot add weaviate embedded before that is implemented. I created a ticket for this in the weaviate repo: https://github.com/weaviate/weaviate/issues/2955

Please upvote there to show that you're interested in that topic, that helps with prioritization.

Until this is implemented, I can recommend using WSL.

**Comment by BeeChains** [comment]
Upvoting... Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

**Comment by dirkkul** [comment]
Mac OS support added in 3.21.0

**Comment by sansmoraxz** [comment]
Trying to do this in windows redirects to this issue:

https://github.com/weaviate/weaviate-python-client/blob/6b21b60ed53d7a4db8cc89249364e4827b779517/weaviate/embedded.py#L175-L178

Should a separate issue be created?

**Comment by dirkkul** [comment]
please upvote this issue in the weaviate repo if you want windows support: https://github.com/weaviate/weaviate/issues/3315

**Comment by Cdaprod** [comment]
👆

**Comment by FelipeSL** [comment]
waiting

**Comment by jakeparkernet** [comment]
Upvote
