### ISSUE TITLE
Publishing instruction fails

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-python-client#244]
In the [publishing instructions](https://github.com/weaviate/weaviate-python-client/blob/main/publishing.md), step 3 `python setup.py sdist bdist_wheel` fails with this error after a fresh git clone:

```
❯ python3 setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

After removing `bdist_wheel`, running steps 3, 4 and 9 did lead to successfully installing the package locally.

**Comment by dirkkul** [comment]
see my comments on your PR
