### ISSUE TITLE
Broken example for schema.Schema.create

### ISSUE THREAD

**Issue by dandv** [weaviate/weaviate-python-client#257]
The example for [Schema.create](https://weaviate-python-client.readthedocs.io/en/stable/weaviate.schema.html#weaviate.schema.Schema.create) seems copy-pasted from [create_class](https://weaviate-python-client.readthedocs.io/en/stable/weaviate.schema.html#weaviate.schema.Schema.create_class) and fails at runtime with
> weaviate.exceptions.SchemaValidationException: Each schema has to have "classes" in the first level of the JSON format file/parameter/object

**Comment by dandv** [comment]
BTW, submitting the PR wasn't as easy as it should be, because the "Edit on GitHub" link on that page leads to https://github.com/semi-technologies/weaviate-python-client/blob/7ac0b09213c472fbab3c46278547b8293c8f235a/docs/weaviate.schema.rst instead of the [actual code](https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/schema/crud_schema.py#L72-L88).

Any way to make this easier for less motivated contributors?

**Comment by dirkkul** [comment]
https://docs.readthedocs.io/en/stable/guides/edit-source-links-sphinx.html should be possible! Would you like to add that? :)
