### ISSUE TITLE
Authentication with additional_headers is not possible

### ISSUE THREAD

**Issue by dennis-ge** [weaviate/weaviate-python-client#265]
**Bug Description**

When creating a new client, setting the `Authorization` header via the `additional_headers` parameter is not working:

```python
weviate_client = client.Client(
        url="http://localhost:8080",
        additional_headers={"Authorization:": "Bearer xyz"},
    )
```

The following error is thrown:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv/lib/python3.10/site-packages/weaviate/client.py", line 146, in __init__
    self._connection = Connection(
  File ".../venv/lib/python3.10/site-packages/weaviate/connect/connection.py", line 580, in __init__
    super().__init__(
  File ".../venv/lib/python3.10/site-packages/weaviate/connect/connection.py", line 117, in __init__
    self._create_session(auth_client_secret)
  File ".../venv/lib/python3.10/site-packages/weaviate/connect/connection.py", line 180, in _create_session
    raise AuthenticationFailedException(msg)
weaviate.exceptions.AuthenticationFailedException: "No login credentials provided. The weaviate instance at http://localhost:8080 requires login credentials.

                    Please check our documentation at https://weaviate.io/developers/weaviate/client-libraries/python#authentication
                    for more information about how to use authentication.
```

This error is thrown in the [_create_session](https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/connect/connection.py#L119-L185) method because the used weviate instance has an OIDC configuration but no `auth_client_secret` was provided. 

I also saw that a previous issue (https://github.com/weaviate/weaviate-python-client/issues/177) already adressed this, but the proposed solution didn't fix it.

**Proposed Solution**

The case when an `Authorization` header is present in the `additional_headers` dict can be handled in the same way as the newly introduced `AuthApiKey` at the top of the [_create_session](https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/connect/connection.py#L130-L133).  If the header is present in the private `_headers` dict of the `BaseConnection`, a new session can be created and the method can be exited.

I can also provide a PR if wanted.

**Comment by dirkkul** [comment]
> I can also provide a PR if wanted.

That would be great, your proposed solutions sounds good. Please with a test in [this file](mock_tests/test_auth.py) :)
