### ISSUE TITLE
Chaining where filters

### ISSUE THREAD

**Issue by AmosDinh** [weaviate/weaviate-python-client#277]
Would it be possible to add this feature?
I know I can achieve this by using the "and" operator
For instance, here:

```
 where1 = {
       "path": ['pageNumber'],
      "operator": "Equal",
      "valueInt": 1,
  }
  
  where2 = {
       "path": ['docNumber'],
      "operator": "Equal",
      "valueInt": 2,
  }
  q = (self._client.query
       .get(class_name,'pageNumber')
       .with_where(where1)
       .with_where(where2)
       )
```

the first filter is overwritten.

The usecase for me is that I can define different base queries that may include where filters. Then I can modify these base queries without overwriting the already specified where filters.

**Comment by axeloh** [comment]
My workaround for dynamically adding filters is to use `functools.reduce` to combine the filters upfront (note this is Python client v4 syntax): 
```python
from functools import reduce

filters = []
if something: 
    filters.append(Filter(...))
elif something_else:
    filters.append(Filter(...))

combined_filter = reduce(lambda x, y: x & y, filters)
chunks.query.fetch_objects(filters=combined_filter)
```

**Comment by dirkkul** [comment]
this should be much easier with the new v4 syntax - please give it a try (still in beta) :)
