### ISSUE TITLE
Feature Request: Raise exception if graphql query is invalid

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate-python-client#283]
Running `do()` on a query raises a [connection error or unexpected status code exception](https://github.com/weaviate/weaviate-python-client/blob/7dfdd9bf44b51c134154c72ddff97042b15347db/weaviate/gql/filter.py#L70-L74).

We should consider raising a malformed gql error too.

The use case is that in partner frameworks, it is common to wrap a call to query weaviate in a try block and then raise and error if the results has 'errors'. In this case, the error usually stems from user querying a property that does not exist or provide a graphql query with syntax errors.

**Comment by dirkkul** [comment]
as we're moving to GRPC, I'll close this issue
