### ISSUE TITLE
GraphQL Get: Query all properties if none are given

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate-python-client#288]
Currently get queries require to list all properties that should be returned and if no properties are given, the query returns an error. 

```
client.query.get(class_name="CLASS", properties=["PROP1", "PROP2"]).do()
```

Instead of returning an error, the client should get all non-reference properties from the schema if `properties=None` and include those by default

**Comment by meetagrawal09** [comment]
@dirkkul, can you help me how can I get access to the schema to get all properties for the specific class : 

If any of the below approaches might work : 

1. Updating it to code segment below : 
      ```
      if properties is None:
             schema = client.schema.get(class_name=class_name)
             properties = schema["properties"]
    ```
    This update should be made before calling the constructor for `GetBuilder` since `client` is not accessible there.

2. Adding `"*"` to the properties list. 

If you can help me with some resources and point me to the right direction that would be great : )

**Comment by dirkkul** [comment]
I'd go for 1, I'm pretty sure that we do not have support for `*` in weaviate.

But keep in mind that we only want to use non-reference properties (eg those whose datatype starts with a small letter)

**Comment by dirkkul** [comment]
we are doing this in the new client, closing this for now
