### ISSUE TITLE
Add support for None scope

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate-python-client#292]
**The issue**

This works:

```
import weaviate

resource_owner_config = weaviate.AuthClientPassword(
  username = "username",
  password = "password",
  scope = "offline_access" 
  )

client = weaviate.Client(url, auth_client_secret=resource_owner_config)
```

but this:

```
import weaviate

resource_owner_config = weaviate.AuthClientPassword(
  username = "username",
  password = "password",
  scope = None 
  )

client = weaviate.Client(url, auth_client_secret=resource_owner_config)
```

throws:

> File [/opt/conda/lib/python3.10/site-packages/weaviate/connect/authentication.py:96](https://vscode-remote+ssh-002dremote-002bmsh-002dexperiments.vscode-resource.vscode-cdn.net/opt/conda/lib/python3.10/site-packages/weaviate/connect/authentication.py:96), in _Auth._get_session_user_pw(self, config)
>      94 def _get_session_user_pw(self, config: AuthClientPassword) -> OAuth2Session:
>      95     scope: List[str] = self._default_scopes.copy()
> ---> 96     scope.extend(config.scope)
>      97     session = OAuth2Session(
>      98         client_id=self._client_id,
>      99         token_endpoint=self._token_endpoint,
>    (...)
>     102         default_timeout=AUTH_DEFAULT_TIMEOUT,
>     103     )
>     104     token = session.fetch_token(username=config.username, password=config.password)
> TypeError: 'NoneType' object is not iterable

despite the type hint in AuthClientPassword saying None scope is allowed:

```
    username: str
    password: str
    scope: Optional[SCOPES] = field(default_factory=lambda: ["offline_access"])
```

**Comment by dirkkul** [comment]
just tried it out again and it does not produce the error anymore. Please reopen in case you can still reproduce it
