### ISSUE TITLE
Automatically escape newlines in `valueText` and `valueString` in where filters

### ISSUE THREAD

**Issue by trengrj** [weaviate/weaviate-python-client#294]
GraphQL will otherwise throw an error. Would also be nice if this was generic in that any string could safely have newlines in it.

Slack ref https://weaviate.slack.com/archives/C017EG2SL3H/p1681749649215729

**Comment by manu156** [comment]
Hi @trengrj , wouldn't it be better if we escape all characters starting with `\` ?
something like:
```python
>>> def escape_unicode(str):
...     return str.encode('unicode_escape').decode()
... 

>>> escape_unicode("hi\ngg")
'hi\\ngg'
>>> escape_unicode("hi\\ngg")
'hi\\\\ngg'
```
