### ISSUE TITLE
weaviate 1.19: validate_schema.py's PROPERTY_KEYS should includes "indexFilterable" and "indexSearchable"

### ISSUE THREAD

**Issue by washanhanzi** [weaviate/weaviate-python-client#315]
weaviate 1.19 introduces two new property keys: indexFilterable, indexSearchable.

This breaks 3.17 python client with invalid property keys when calling `client.schema.create()` because of `validate_schema.py`'s `PROPERTY_KEYS`.

And I think there should be a way to check weaviate version before validate the schema.

Or there should be a warning when using python client to connect to weaviate instance with version above 1.18.

This pr check for a minimum threshold #299 , maybe a maximum threshold should also be checked.

https://github.com/weaviate/weaviate-python-client/blob/83457c40346956c556549736168460bb81c894d0/weaviate/schema/validate_schema.py#LL21C5-L21C5

**Comment by dirkkul** [comment]
Hi, I fixed this in 3.17.1.

I decided against adding a warning for a maximum version, in general old versions of the python client should work with new weaviate versions, you just cannot expect new features to work. But I'm no sure if we need to validate the schema on the client side. Weaviate is doing that anyways and it might make more sense to just pass on the result of that validation
