### ISSUE TITLE
GroupBy does not group under multiple properties

### ISSUE THREAD

**Issue by aledelunap** [weaviate/weaviate-python-client#351]
When passing a list of properties (containing more than one) to `with_group_by()` the query execution results in an error. For example, with the final query being:

```
{Get{Class(nearText: {concepts: ["credit card"]} groupBy:{path:["product_group","product_name"], groups:3, objectsPerGroup:2}){_additional {
        group {
          hits{
            section_title
            information_type
            content
            _additional {
                  id
                }
          }
        }
       id }}}}
```

The execution returns the following error:

```
{'data': {'Get': {'Class': None}},
 'errors': [{'locations': [{'column': 6, 'line': 1}],
   'message': "explorer: get class: vector search: object vector search at index Index: shard Index_: no such prop with name '' found in class 'Class' in the schema. Check your schema files for which properties in this class are available: unrecognized property: ",
   'path': ['Get', 'Class']}]}
```

It works well when passing a single property, but crashes when adding multiple.

The function docstring states the following: 
```
properties: List[str]
    Properties to group by
```
Meaning it should support multiple properties.

Am I missing something in how to correctly use `with_group_by()`?

**Comment by dirkkul** [comment]
@antas-marcin you recently added support for this, could you have a look?

**Comment by antas-marcin** [comment]
@aledelunap you can group by only by 1 class's property, either it's a simple property or a cross-reference property (but not cross-reference's internal property) please check [here](https://weaviate.io/developers/weaviate/api/graphql/get#groupby-argument)

`path` property is defined as an `array` bc in the future it will be possible to group by cross-reference's internal property (it will able to run group by for example with `path: ["hasArticle", "Article", "title"]`) but for now you can only group by cross-reference (like so: `path: ["hasArticle"]` or a simple property
