### ISSUE TITLE
Typo on error message Please install it with `pip instal weaviate-client`

### ISSUE THREAD

**Issue by levalencia** [weaviate/weaviate-python-client#363]
When weaviate client is not installed I get this error, the instal is missing an l.

ValueError: Could not import weaviate python package. Please install it with `pip instal weaviate-client`

instal is missing an L.

**Comment by dirkkul** [comment]
Hi @levalencia ,

from where is that error? If the client is not installed the error message is not from us

**Comment by levalencia** [comment]
the error is when trying to use the client without being installed, so is maybe a pip typo?

**Comment by dirkkul** [comment]
I assume it is from a different project that uses the weaviate client, but it is hard to tell. Are you using jina or haystack or something like that?

**Comment by levalencia** [comment]
langchain. probably is from their wrapper then

**Comment by levalencia** [comment]
Not from weaviate client

**Comment by dirkkul** [comment]
it is from here: https://github.com/hwchase17/langchain/blob/d50de2728f95df0ffc59c538bd67e116a8e75a53/langchain/vectorstores/weaviate.py#L49
