### ISSUE TITLE
Pypi Package Version Check (Air-gapped Environment)

### ISSUE THREAD

**Issue by zirota** [weaviate/weaviate-python-client#372]
Hello, is there any way to disable package version checking? The `PYPI_PACKAGE_URL` will not be accessible in an air-gapped environment. All the client request will hang indefinitely at this step

https://github.com/weaviate/weaviate-python-client/blob/af2c9c13310b4b5aea157c5461418359b0e13ad2/weaviate/connect/connection.py#L667-L671

**Comment by dirkkul** [comment]
Could you try out this wheel? https://github.com/weaviate/weaviate-python-client/actions/runs/5483600730?pr=373

I added a 1s timeout for the pypi, does that work for you?

**Comment by zirota** [comment]
No it does not, the timeout ensures that an error gets thrown indicating that the connection to pypi fails. But if my client is inside an air-gapped environment with no access to pypi I would still not be able to connect to my running weaviate server because the package versioning check will fail.

**Comment by zirota** [comment]
it works, thanks! @dirkkul

**Comment by dirkkul** [comment]
thanks for getting back! This will be in the next version
