### ISSUE TITLE
Cannot change size

### ISSUE THREAD

**Issue by msj121** [weaviate/weaviate-python-client#400]
I get the following error when trying to add a large amount of data, like a large blog:
`
could not get vector from remote: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (62741084 vs. 4194304)"}]}.
`

I am using `self.client.data_object.update`

Is there a way to increase the size? On the server I am using text2vect-contextionary. It is an 8gb Ram server (no gpu).

Also another server (with gpu) responds "Object was not updated." is there a way to get more information?

**Comment by dirkkul** [comment]
could you post a full example? The data_object call doesn't go through GRPC so I'm a bit confused on how that could happen.

**Comment by msj121** [comment]
Thanks! I was able to narrow down the issue... this error was actually passed along via weaviate itself erroring. It wasn't showing me the error before, but I put on debug logs and now I can see that's the culprit in one of the communications via docker. Great library btw. Thank you
