### ISSUE TITLE
Provide `use_buffering` optimisation argument to `file_encoder_b64` function

### ISSUE THREAD

**Issue by tsmith023** [weaviate/weaviate-python-client#432]
As mentioned originally in https://github.com/weaviate/weaviate-python-client/pull/384#discussion_r1299812307, allowing users to specify that they'd like to use file read buffering as part of their I/O methods for encoding files to base64 before mutating to Weaviate would likely be highly beneficial in high performance use-cases.

**Comment by dirkkul** [comment]
Done in the new client
