### ISSUE TITLE
self._server_version = self.get_meta()["version"]  pipy.org connection timeout

### ISSUE THREAD

**Issue by landerson85** [weaviate/weaviate-python-client#550]
weaviate.Client(weaviate_url, auth_client_secret=auth, timeout_config=(30, 60))

 self._server_version = self.get_meta()["version"]
        if self._server_version < "1.14":
            _Warnings.weaviate_server_older_than_1_14(self._server_version)
        if is_weaviate_too_old(self._server_version):
            _Warnings.weaviate_too_old_vs_latest(self._server_version)

        try:
            pkg_info = requests.get(PYPI_PACKAGE_URL, tiFmeout=PYPI_TIMEOUT).json()
            pkg_info = pkg_info.get("info", {})
            latest_version = pkg_info.get("version", "unknown version")
            if is_weaviate_client_too_old(client_version, latest_version):
                _Warnings.weaviate_client_too_old_vs_latest(client_version, latest_version)
        except (RequestsConnectionError, JSONDecodeError, ReadTimeout):
            pass  # air-gaped environments

If there is an exception when connecting to pypi. org, it will directly report an exception. However, in reality, the judgment of this version is not very meaningful. It is already the latest version during installation. Why do we need to obtain a version every time we connect? For such a large product, it feels a bit incredible that this critical entry point has made such an error

**Comment by dirkkul** [comment]
> If there is an exception when connecting to pypi. org, it will directly report an exception. 

You just posted the code that catches the exceptions `except (RequestsConnectionError, JSONDecodeError, ReadTimeout):` if there is anything we missed, I'm happy to add it.

> meaningful. It is already the latest version during installation. Why do we need to obtain a version every time we connect?

Because a LOT of issues are because of old versions. It is the last version at ⁄nstallation, but many people still use that version 5 months later.

**Comment by tsmith023** [comment]
Also `requirements.txt` and `pyproject.toml` files are very rarely updated to use the latest versions willingly
