### ISSUE TITLE
Batch results are not reliably returned on multiple calls

### ISSUE THREAD

**Issue by flash1293** [weaviate/weaviate-python-client#577]
When sending manual batches, errors are not reliably returned from the `batch.create_objects` method if it's called multiple times in succession:

```
client.schema.create_class({"class": "Retrytest"})
for i in range(10):
   client.batch.add_data_object({"name ": "Broken object"}, "Retrytest")
   result = client.batch.create_objects()
   print("return:")
   print(result)
   print("-------------")

client.schema.delete_class("Retrytest")
```

This returns:
```
{'error': [{'message': "'name ' is not a valid property name. Property names in Weaviate are restricted to valid GraphQL names, which must be "/[_A-Za-z][_0-9A-Za-z]*/"., no such prop with name 'name ' found in class 'Retrytest' in the schema. Check your schema files for which properties in this class are available"}]}
return:
[{'class': 'Retrytest', 'creationTimeUnix': 1698053283413, 'id': '2a01f682-5fb1-4c92-9e6c-9abf326c1fc2', 'lastUpdateTimeUnix': 1698053283413, 'properties': {'name ': 'Broken object'}, 'deprecations': None, 'result': {'errors': {'error': [{'message': "'name ' is not a valid property name. Property names in Weaviate are restricted to valid GraphQL names, which must be "/[_A-Za-z][_0-9A-Za-z]*/"., no such prop with name 'name ' found in class 'Retrytest' in the schema. Check your schema files for which properties in this class are available"}]}, 'status': 'FAILED'}}]
-------------
{'error': [{'message': "'name ' is not a valid property name. Property names in Weaviate are restricted to valid GraphQL names, which must be "/[_A-Za-z][_0-9A-Za-z]*/"., no such prop with name 'name ' found in class 'Retrytest' in the schema. Check your schema files for which properties in this class are available"}]}
return:
[]
-------------
```

The Weaviate client is always printing an error, but it won't return it on the second run (`result` is `[]`).

Expected behavior:
The error that's logged away should also be returned every time.

**Comment by flash1293** [comment]
cc @hsm207

**Comment by flash1293** [comment]
Thanks @tsmith023 for suggesting how to work around the issue - however does this mean that `client.batch.create_objects` will never reliably return the status of the objects in the batch and that's by design?

**Comment by flash1293** [comment]
Thanks for the response!

>  I think what you're observing is this non-deterministic flow since some of your calls are sending batches in the background and others aren't

Could you elaborate on this? I assumed that `create_objects` would join all threads and return with the full set of results for the processed batch, but it seems like this is not the case. Is the return value of `create_objects` ever reliable if dynamic isn't set to false like this?

**Comment by tsmith023** [comment]
>Could you elaborate on this?

- `client.batch` is dynamic by default
- When in dynamic, batches are sent as fast as possible depending on server load
- `.add_data_object` makes requests under-the-hood within threads during this process
- These requests clear the internal batching state so when you call `.create_data_object` again, there's nothing to send
- When running in dynamic, you need to provide a callback function to `.configure(callback=)` if you want to process errors
    - The default callback is [here](https://github.com/weaviate/weaviate-python-client/blob/main/weaviate/util.py#L565), which is where the logging you're observing occurs
- Otherwise, provided manual-mode is enabled, errors will be returned by `.create_objects`

>I assumed

Dangerous business 😜

**Comment by flash1293** [comment]
> > I assumed

> Dangerous business 😜

Fair 😆  That makes a lot of sense, thanks for the details.

In the spirit of making the client easier to use, maybe `create_objects` should return an error when used together with dynamic batching as it will always cause confusing behavior if I'm understanding correctly.

**Comment by tsmith023** [comment]
That's a good idea! I'll make a separate issue describing that enhancement and then close this in favour of that one 😁
