### ISSUE TITLE
Add Support  for `object[]` data type

### ISSUE THREAD

**Issue by deven298** [weaviate/weaviate-python-client#599]
I am trying to create a class object with the schema (provided below) with one of the data-types as `object[]`. However, when I print the schema the detected data-type of my `metadata` field becomes `text`. And then I check the code and noticed that python package does not support `object[]` data-type ([code](https://github.com/weaviate/weaviate-python-client/blob/c68d077ca572b50e269c8ffde4294911f479c853/weaviate/schema/crud_schema.py#L46)). Can someone add the support for this data-type. (Ref: [func](https://github.com/weaviate/weaviate-python-client/blob/c68d077ca572b50e269c8ffde4294911f479c853/weaviate/schema/crud_schema.py#L1009))

```
 {'dataType': ['text'], 'description': "This property was generated by Weaviate's auto-schema feature on Tue Oct 31 16:07:28 2023", 'indexFilterable': True, 'indexSearchable': True, 'name': 'metadata', 'tokenization': 'word'}]
```

```python
# schema
class_obj = {
    "classes": [
        {
            "class": self.index_name,
            "vectorizer": "none",
            "properties": [
                {
                    "name": "identifier",
                    "dataType": ["text"],
                },
                {
                    "name": "text",
                    "dataType": ["text"],
                },
                {
                    "name": "metadata",
                    "dataType": ["object[]"],
                    "nestedProperties": [
                        {
                            "name": "data_type",
                            "dataType": ["text"],
                        },
                        {
                            "name": "doc_id",
                            "dataType": ["text"],
                        },
                        {
                            "name": "url",
                            "dataType": ["text"],
                        },
                        {
                            "name": "hash",
                            "dataType": ["text"],
                        },
                        {
                            "name": "app_id",
                            "dataType": ["text"],
                        },
                    ],
                },
            ],
        }
    ]
}
```

**Comment by tsmith023** [comment]
Hi @deven298, for clarity on your problem, what versions of the Python client and Weaviate server are you using?

**Comment by deven298** [comment]
Hey @tsmith023 

I am using `weaviate-client` v3.24.2 python package.

**Comment by tsmith023** [comment]
And what about your Weaviate server version?

**Comment by deven298** [comment]
My weaviate server version is `1.22.1`

**Comment by tsmith023** [comment]
Okay, that makes sense then!

Please update your Python client to `v3.25.2` that has support for `object` and `object[]` types 😁
