### ISSUE TITLE
Unsupported EmbeddedDB

### ISSUE THREAD

**Issue by alsaif1431** [weaviate/weaviate-python-client#612]
check_supported_platform
    raise WeaviateStartUpError(
weaviate.exceptions.WeaviateStartUpError: Windows is not supported with EmbeddedDB. Please upvote the feature request if you want this: https://github.com/weaviate/weaviate-python-client/issues/239

I was trying to do a Verba Start on my Windows Machine by setting up a OPENAI_API_KEY
but it threw the above error.

**Comment by tsmith023** [comment]
Hi @alsaif1431, Weaviate does not currently compile on Windows so you won't be able to run `EmbeddedDB` on your machine natively like this. Upvote this issue to add your support to this feature: https://github.com/weaviate/weaviate/issues/3315

**Comment by ddimaio** [comment]
what is the alternative to run verba then?

**Comment by alsaif1431** [comment]
Thanks @tsmith023.. Got your point!
