### ISSUE TITLE
`query.fetch_objects` and `collection.iterator()` fail on geoCoordinates type

### ISSUE THREAD

**Issue by mrisher** [weaviate/weaviate-python-client#647]
Hi:
There may be a syntax I'm missing, but when my schema includes a geoCoordinates datatype, I cannot use most of the examples in the docs. If I explicitly exclude the field with `return_properties` then my query works, but how can I get that missing field?

For example, my `Event` collection has a field called `coordinates`:
```
GeoCoordinates as latitude and longitude in decimal form

type EventcoordinatesGeoCoordinatesObj {
latitude: Float
longitude: Float
}
```

If I run a query without limiting the return properties:
```python
collection = source_client.collections.get("Event")
for item in collection.iterator():
    print(print(item.uuid))
```

I get:
```
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/weaviate/collections/grpc/query.py](https://localhost:8080/#) in __call(self)
    442             res: SearchResponse  # According to PEP-0526
--> 443             res, _ = self._connection.grpc_stub.Search.with_call(
    444                 search_get_pb2.SearchRequest(

7 frames
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "creating non-ref-prop struct: proto: invalid type: *models.GeoCoordinates"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2023-12-12T11:08:52.758958527+00:00", grpc_status:2, grpc_message:"creating non-ref-prop struct: proto:\xc2\xa0invalid type: *models.GeoCoordinates"}"
>

During handling of the above exception, another exception occurred:

WeaviateQueryException                    Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/weaviate/collections/grpc/query.py](https://localhost:8080/#) in __call(self)
    530 
    531         except grpc.RpcError as e:
--> 532             raise WeaviateQueryException(e.details())
    533 
    534     def _metadata_to_grpc(self, metadata: _MetadataQuery) -> search_get_pb2.MetadataRequest:

WeaviateQueryException: Query call failed with message creating non-ref-prop struct: proto: invalid type: *models.GeoCoordinates.
```

Same goes for query:
```python
collection = source_client.collections.get("Event")
response = collection.query.fetch_objects(
    filters=wvc.Filter(["reviews", "EventReview", "review_len"]).greater_than(25),
    limit=2,
    # UNCOMMENT to see error
    # return_properties=[
    #     "name",
    #     "venue",
    #     "start",
    #     "end",
    #     wvc.FromReference(
    #         link_on="reviews",
    #         return_properties=["text"],
    #     )
    # ],
)
```

Is there a missing syntax in the docs for sub-properties or nested properties or sim?

**Comment by tsmith023** [comment]
Hi @mrisher, thanks for trying out the v4 _beta_ client and pushing it to its limits! You've indeed found one of these as we have not implemented `GeoCoordinates` support in the v4 client as yet. However, we are planning on releasing a new version alongside the impending Weaviate `1.23` release that will support this data type!

I will leave this issue open until all versions have been released and your MRE above is fixed!

**Comment by dirkkul** [comment]
> Do you have a roadmap date for 1.23?

not sure if there is an official date yet, but I think at some point next week

> Also can we add something to the [client docs](https://weaviate.io/developers/weaviate/client-libraries/python) on known, unsupported features ?

it is a very iterative approach currently and any docs would be outdated quickly. Best thing would be to do a github issue if things do not work as expected.

>  I'm also hitting an issue trying to filter on a date

I'll have a look!

Geoocordinates are merged btw

**Comment by dirkkul** [comment]
Batch delete with timestamps also works, however it is very difficult to use in the current version. I think you can use timestamps eg what is currently returned by object.metadata.creation_time

In the next beta version which comes with 1.23 you can do 
```
    collection.data.delete_many(
        where=FilterMetadata.ByCreationTime.less_or_equal(*datetime-object*)
    )
```

Note that the return value of object.metadata.creation_time will change to a datetime-object in the next beta version

Will close this issue, thanks for testing and please open a new one for any new issues :)
