### ISSUE TITLE
cross-reference urls appear to be case-sensitive

### ISSUE THREAD

**Issue by SavvasMohito** [weaviate/weaviate-python-client#714]
## Description
Hi, I am using the latest python client v4.4b6 with the latest weaviate server v1.23.2 running on docker. I have noticed a weird behaviour that affects the cross-reference functionality. When inserting a new object into a collection, the UUID of it is always saved in lowercase, even if you set it in uppercase. This shouldn't affect anything as [UUIDs are not case sensitive ](https://www.uuidtools.com/what-is-uuid#:~:text=Are%20UUIDs%20Case%2Dsensitive%3F).

When adding a cross-reference to an object (either during or after object creation), the referenced target UUID is not transformed to lowercase. As a result, if I add a cross-reference using a uppercase UUID, weaviate will not be able to retrieve the cross-referenced object because the reference URL includes the id in uppercase but the actual object is stored with a lowercase id by default.

### Steps to reproduce
```python
import weaviate
import weaviate.classes as wvc

client = weaviate.connect_to_local()

# Create collections
a_collection = client.collections.create(
    "Answer",
    properties=[wvc.Property(name="text", data_type=wvc.DataType.TEXT)]
)

q_collection = client.collections.create(
    "Question",
    properties=[wvc.Property(name="text", data_type=wvc.DataType.TEXT)],
    references=[wvc.ReferenceProperty(name="hasAnswer", target_collection="Answer")]
)

# Add answer object
a_collection.data.insert(uuid="4E5CD755-4F43-44C5-B23C-0C7D6F6C21E6", properties={"text": "this is the answer"})
# Add question with uppercase reference
q_collection.data.insert(properties={"text": "question with uppercase reference"}, references={"hasAnswer": wvc.Reference.to(uuids="4E5CD755-4F43-44C5-B23C-0C7D6F6C21E6")})
# Add question with lowercase reference
q_collection.data.insert(properties={"text": "question with lowercase reference"}, references={"hasAnswer": wvc.Reference.to(uuids="4E5CD755-4F43-44C5-B23C-0C7D6F6C21E6".lower())})

# Query the two question objects
q_collection.query.fetch_objects(limit=2, return_references=[wvc.QueryReference(link_on="hasAnswer", return_properties=["text"])]).objects
```

query result: the first object does not fetch the cross-reference but the second one does
```output
[_Object(uuid=_WeaviateUUIDInt('3272b239-78d2-4615-b887-c28c23753bb4'), metadata=_MetadataReturn(creation_time=None, last_update_time=None, distance=None, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None), properties={'text': 'is this the question?'}, references=None, vector=None),
 _Object(uuid=_WeaviateUUIDInt('c3647945-4216-4fd0-98ae-5bb3c41466e2'), metadata=_MetadataReturn(creation_time=None, last_update_time=None, distance=None, certainty=None, score=None, explain_score=None, is_consistent=None, rerank_score=None), properties={'text': 'question with lowercase reference'}, references={'hasAnswer': <weaviate.collections.classes.internal._CrossReference object at 0x7f88581edab0>}, vector=None)]
```

### My thoughts
I am not sure if this is a client issue or a weaviate issue. I believe that uuids should not be treated as case sensitive because it creates a lot of confusion and also does not comply with the spec. This issue can be easily fixed is the client automatically transforms uuids to lowercase.

**Comment by dirkkul** [comment]
It is a weaviate problem - I made a PR that should fix it

**Comment by dirkkul** [comment]
merged, will be in the next release :)

**Comment by SavvasMohito** [comment]
Great, thanks for your help @dirkkul !
