### ISSUE TITLE
Making embedded Weaviate less verbose

### ISSUE THREAD

**Issue by meherhendi** [weaviate/weaviate-python-client#716]
I'm having an issue with the Weaviate embedded outputting too much verbose Openapi/swagger logs,
is it possible to reduce the verbosity of this output?

This is an example of the output:

> operation: spec.Operation{VendorExtensible:spec.VendorExtensible{Extensions:spec.Extensions{"x-available-in-mqtt":false, "x-available-in-websocket":false, "x-serviceIds":[]interface {}{"weaviate.local.manipulate"}}}, OperationProps:spec.OperationProps{Description:"Update an individual data object based on its class and uuid.", Consumes:[]string(nil), Produces:[]string(nil), Schemes:[]string(nil), Tags:[]string{"objects"}, Summary:"Update a class object based on its uuid", ExternalDocs:(*spec.ExternalDocumentation)(nil), ID:"objects.class.put", Deprecated:false, Security:[]map[string][]string(nil), Parameters:[]spec.Parameter{spec.Parameter{Refable:spec.Refable{Ref:spec.Ref{Ref:jsonreference.Ref{referenceURL:(*url.URL)(nil), referencePointer:jsonpointer.Pointer{referenceTokens:[]string(nil)}, HasFullURL:false, HasURLPathOnly:false, HasFragmentOnly:false, HasFileScheme:false, HasFullFilePath:false}}}, CommonValidations:spec.CommonValidations{Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]interface {}(nil)}, SimpleSchema:spec.SimpleSchema{Type:"string", Nullable:false, Format:"", Items:(*spec.Items)(nil), CollectionFormat:"", Default:interface {}(nil), Example:interface {}(nil)}, VendorExtensible:spec.VendorExtensible{Extensions:spec.Extensions(nil)}, ParamProps:spec.ParamProps{Description:"", Name:"className", In:"path", Required:true, Schema:(*spec.Schema)(nil), AllowEmptyValue:false}}, spec.Parameter{Refable:spec.Refable{Ref:spec.Ref{Ref:jsonreference.Ref{referenceURL:(*url.URL)(nil), referencePointer:jsonpointer.Pointer{referenceTokens:[]string(nil)}, HasFullURL:false, HasURLPathOnly:false, HasFragmentOnly:false, HasFileScheme:false, HasFullFilePath:false}}}, CommonValidations:spec.CommonValidations{Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]interface {}(nil)}, SimpleSchema:spec.SimpleSchema{Type:"string", Nullable:false, Format:"uuid", Items:(*spec.Items)(nil), CollectionFormat:"", Default:interface {}(nil), Example:interface {}(nil)}, VendorExtensible:spec.VendorExtensible{Extensions:spec.Extensions(nil)}, ParamProps:spec.ParamProps{Description:"The uuid of the data object to update.", Name:"id", In:"path", Required:true, Schema:(*spec.Schema)(nil), AllowEmptyValue:false}}, spec.Parameter{Refable:spec.Refable{Ref:spec.Ref{Ref:jsonreference.Ref{referenceURL:(*url.URL)(nil), referencePointer:jsonpointer.Pointer{referenceTokens:[]string(nil)}, HasFullURL:false, HasURLPathOnly:false, HasFragmentOnly:false, HasFileScheme:false, HasFullFilePath:false}}}, CommonValidations:spec.CommonValidations{Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]interface {}(nil)}, SimpleSchema:spec.SimpleSchema{Type:"", Nullable:false, Format:"", Items:(*spec.Items)(nil), CollectionFormat:"", Default:interface {}(nil), Example:interface {}(nil)}, VendorExtensible:spec.VendorExtensible{Extensions:spec.Extensions(nil)}, ParamProps:spec.ParamProps{Description:"", Name:"body", In:"body", Required:true, Schema:(*spec.Schema)(0xc0032cab40), AllowEmptyValue:false}}, spec.Parameter{Refable:spec.Refable{Ref:spec.Ref{Ref:jsonreference.Ref{referenceURL:(*url.URL)(nil), referencePointer:jsonpointer.Pointer{referenceTokens:[]string(nil)}, HasFullURL:false, HasURLPathOnly:false, HasFragmentOnly:false, HasFileScheme:false, HasFullFilePath:false}}}, CommonValidations:spec.CommonValidations{Maximum:(*float64)(nil), ExclusiveMaximum:false, Minimum:(*float64)(nil), ExclusiveMinimum:false, MaxLength:(*int64)(nil), MinLength:(*int64)(nil), Pattern:"", MaxItems:(*int64)(nil), MinItems:(*int64)(nil), UniqueItems:false, MultipleOf:(*float64)(nil), Enum:[]interface {}(nil)}, SimpleSchema:spec.SimpleSchema{Type:"string", Nullable:false, Format:"", Items:(*spec.Items)(nil), CollectionFormat:"", Default:interface {}(nil), Example:interface {}(nil)}, VendorExtensible:spec.VendorExtensible{Extensions:spec.Extensions(nil)}, ParamProps:spec.ParamProps{Description:"Determines how many replicas must acknowledge a request before it is considered successful", Name:"consistency_level", In:"query", Required:false, Schema:(*spec.Schema)(nil), AllowEmptyValue:false}}}, Responses:(*spec.Responses)(0xc0032d04b0)}}

**Comment by dirkkul** [comment]
We are planning on doing this at some point, but don't have the time for it now. There is already an issue here: https://github.com/weaviate/weaviate-python-client/issues/346
