### ISSUE TITLE
Using `with_near_object()` results in invalid GraphQL query string

### ISSUE THREAD

**Issue by ilyasotkov** [weaviate/weaviate-python-client#80]
When I try to run this code
```py
query: str = (
    client.query.get(
        class_name="Article", properties=["name"]
    )
    .with_near_object({"id": "550ef8ad-fa64-40c5-a658-47716644dd11"})
    .build()
)
client.query.raw(query)
```
I get an error like this
```
Syntax Error GraphQL request (1:35) Invalid number, expected digit but got: \"f\".\n\n1: {Get{Article(nearObject: {id: 550ef8ad-fa64-40c5-a658-47716644dd11} ){name}}}\n                                     ^\n"
```

The resulting query is

```
{Get{Article(nearObject: {id: 550ef8ad-fa64-40c5-a658-47716644dd11} ){name}}}
```

the ID here is a string and it should be double-quoted.

The issue in  weaviate-python-client appears to be on this LOC https://github.com/semi-technologies/weaviate-python-client/blob/7a0f01821acccf9a2c32c474e8d728e6e032625e/weaviate/gql/filter.py#L266 and I suspect it could also be present elsewhere in the codebase.

**Comment by StefanBogdan** [comment]
This is fixed in version `3.2.3`.
