### ISSUE TITLE
unable to use with_offset and with_after in weaviate

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [weaviate/weaviate-python-client#806]
I tried latest and 1.22.3 weaviate docker images with weaviate-client  verison of 3.8 but I am unable to use with_after and with_offset option for all data pull. but previously it is possible with weaviate-client=3.25.3 but right now I tried but unable to do it . please help me out asap.
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '9000'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.22.3
    ports:
    - 9000:9000
    volumes:
    - /data2/weaviate/data:/data2/weaviate/data
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/data2/weaviate/data'
      BINARY_PATH: '/data2/weaviate/cache'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'

**Comment by shubhamgajbhiye1994** [comment]
![image](https://github.com/weaviate/weaviate-python-client/assets/32373229/86532cb2-7c77-4387-ae2e-fd6c549c1c40)

**Comment by dirkkul** [comment]
This sounds like a suport request, can you please make a post in our [support forum](https://forum.weaviate.io/)?
