### ISSUE TITLE
AttributeError: 'GetBuilder' object has no attribute 'with_after'

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [weaviate/weaviate-python-client#807]
client.query.get("Candidate",["fcu"]).with_after('000001bd-426e-51bd-9d41-29651e1f7e53').with_limit(5).do()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-e67c56924299> in <module>
----> 1 client.query.get("Candidate",["fcu"]).with_after('000001bd-426e-51bd-9d41-29651e1f7e53').with_limit(5).do()

AttributeError: 'GetBuilder' object has no attribute 'with_after'

**Comment by dirkkul** [comment]
same as the other one - please use the [support forum](https://forum.weaviate.io/)
