### ISSUE TITLE
`Client().schema.contains()` does not accept class schemas

### ISSUE THREAD

**Issue by StefanBogdan** [weaviate/weaviate-python-client#82]
This does not create any schemas:
```python
if not client.schema.contains(class_schema):  
    client.schema.create_class(class_schema)
```
The workaround is:
```python
if not client.schema.contains({'classes': [class_schema]}):  
    client.schema.create_class(class_schema)
```

This needs to be fixed so class schemas alone can be passed.

This is also discussed here: 
 - [x] https://github.com/semi-technologies/weaviate/issues/1721

**Comment by sreedevijain19** [comment]
name class schema is not defined
