### ISSUE TITLE
V4 client does not return the property when the data is null for that property

### ISSUE THREAD

**Issue by amitmadahar** [weaviate/weaviate-python-client#858]
V4 client does not return the property when the data is null for that property. V3 client returns all requested columns irrespective. 

```
QueryClass = 'myCoolClass'
doc_name = 'CoolDoc'
response = client_v3.query.get(
    QueryClass, ["page_content", "col1", "col2", "col3", "col4", "col5"]
    ).with_additional(['id', 'vector']
    ).with_limit(1000
    ).do()

import weaviate.classes as wvc
QueryClass = 'myCoolClass'
doc_name = 'CoolDoc'
collection = client_v4.collections.get(QueryClass)
response = collection.query.fetch_objects(
    return_properties=["page_content", "col1", "col2", "col3", "col4", "col5"],
    include_vector=True,
    limit=1000
) 
```

The two responses are different when col5 is Null. client_v3 is the correct response. col5 is yet to expect data in my case.
Futher, if col4 or col3 have null data intermittently, V4 misses to report them in the response.

**Comment by dirkkul** [comment]
this will be fixed with weaviate 1.24 (in ~1-2 weeks) and client >= 4.4.2
