### ISSUE TITLE
Add input_type support for Cohere v3 models for Client V4

### ISSUE THREAD

**Issue by amitmadahar** [weaviate/weaviate-python-client#859]
Text2vec_cohere v3.0 is supported since v1.22.3. Weaviate VDB implemention support input_type for cohere embeddings and was added here : 
https://github.com/weaviate/weaviate/pull/3749/commits/d6d3461d13b0d11db3be0456cbf6172b899edbcf

But, no references in the documentation on where and how can "input_type" for text2vec_cohere can be defined. 

It would be beneficial to define the "input_type" at the class level so different vector types are not mixed in a same class.

The support for "input_type" is missing in both V3 and V4 clients.

**Comment by tsmith023** [comment]
Hi @amitmadahar, the `inputType` field used by Weaviate is purely internal and is not exposed as part of its API. Weaviate uses `search_document` when creating the vectors of your documents upon object creation and `search_query` when creating the vectors of your queries when using the `nearText` functionality. This is the hard-coded internal implementation and so is immutable by the user
