### ISSUE TITLE
Issue with Base URL and API Version when using AzureOpenAI

### ISSUE THREAD

**Issue by pi-crust** [weaviate/weaviate-python-client#862]
When using Azure OpenAI through Private Org BaseURL, the following error occurs

`ValueError: Error during query: [{'locations': [{'column': 6, 'line': 1}], 'message': 'explorer: get class: vectorize params: vectorize params: vectorize params: vectorize keywords: remote client vectorize: send POST request: Post "https://azure-llm.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2022-12-01": read tcp 100.64.95.5:59158->20.232.91.180:443: read: connection reset by peer', 'path': ['Get', 'OAAIndexOpenAITest']}]`

The program is sending request to `https://azure-llm.openai.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2022-12-01` even after specifying the X-OpenAI-BaseURL". Instead of routing to `https://<baseURL>/openai/deployments/<deploymentID>/chat/completions?api-version=<api-version>`

This is occurring when retrieving the indexed documents from Weaviate.

```
import weaviate

auth_client_secret = weaviate.AuthApiKey(Config.WEAVIATE_READER_APIKEY)
additional_headers = {"X-Azure-Api-Key": Config.OPENAI_API_KEY,
                                      "X-OpenAI-BaseURL":Config.OPENAI_API_BASE,
                                      "X-OpenAI-Organization":Config.OPENAI_ORGANIZATION}
wv_conn = weaviate.Client(url=os.environ["WEAVIATE_URL"],
                                             auth_client_secret=auth_client_secret,
                                             additional_headers=additional_headers)
```

The index is created using create_class

```
vectorizer = "text2vec-openai"
module_config = {vectorizer: {"resourceName": Config.OPENAI_RESOURCE_NAME,
                                                    "baseURL" : Config.OPENAI_API_BASE,
                                                    "deploymentId": Constants.OPENAI_DEPLOYMENT}}
wv_conn.schema.create_class({"class": "temp_class",
                                                      "vectorizer": vectorizer ,
                                                       "moduleConfig": module_config})
```

These updates are made in weaviate repo, see below PRs. Aren't these supposed to be reflected here too? 

https://github.com/weaviate/weaviate/pull/4124
https://github.com/weaviate/weaviate/pull/3966

```Name: weaviate-client
Version: 4.4.2
Summary: A python native Weaviate client
Home-page: https://github.com/weaviate/weaviate-python-client
Author: Weaviate
Author-email: hello@weaviate.io,
License: BSD 3-clause
Location: /Users/vedala/Documents/projects/OA/oa-answers/oaa/lib/python3.9/site-packages
Requires: authlib, grpcio, grpcio-health-checking, grpcio-tools, httpx, pydantic, requests, validators```

**Comment by pi-curst** [comment]
I also get these warnings

/Users/vedala/Documents/projects/OA/oa-answers/oaa/lib/python3.9/site-packages/weaviate/__init__.py:128: DeprecationWarning: Dep010: Importing AuthApiKey from weaviate is deprecated. Please import it from its specific module: weaviate.auth
  _Warnings.root_module_import(name, map_[name])
/Users/vedala/Documents/projects/OA/oa-answers/oaa/lib/python3.9/site-packages/weaviate/warnings.py:158: DeprecationWarning: Dep016: You are using the Weaviate v3 client, which is deprecated.
            Consider upgrading to the new and improved v4 client instead!
            See here for usage: https://weaviate.io/developers/weaviate/client-libraries/python
            
  warnings.warn(

**Comment by dirkkul** [comment]
There is no released version of weaviate that contains that feature, so you cannot use it yet unless you install a local dev version.

you are getting the warnings, because you are using a python client v3 syntax with a v4 client. Please check the link in the warning.

**Comment by tsmith023** [comment]
Hi @pi-curst, to help with our diagnostics can you try specifying the additional headers as `X-Openai-Baseurl` and `X-Openai-Organization`? Looking at the Weaviate code source, these may be case sensitive

**Comment by dirkkul** [comment]
I think this would better fit into our support forum at https://forum.weaviate.io/

**Comment by pi-crust** [comment]
Is there any update on this issue?
