### ISSUE TITLE
Reconsider your definition of private and public interface please

### ISSUE THREAD

**Issue by pafi-code** [weaviate/weaviate-python-client#882]
When trying to use this client in your own code with type hints, you are facing the challenge of adding typehints for specific return objects. For example `collection.query.fetch_objects()` has a private return type of `QueryReturn` which only exists in `weaviate.collections.classes.internals`. So you are exposing your private interface via your public interface, which doesn't make sense.

Hope it's understandable.

Cheers :beer:

**Comment by dirkkul** [comment]
H, all types should be available as TypeAlias in `weaviate/outputs` and its subfolders - QueryReturnType is available as `weaviate.outputs.query.QueryReturnType`. Does that help?

**Comment by pafi-code** [comment]
Well at least to some degree. But this doesn't really solve everything. For example I can't really find a public type for object from `collection.query.fetch_objects().objects`.

**Comment by tsmith023** [comment]
Ah, this one is missing from the `outputs` module, as are some others on reflection. We'll add them to it in the next patch!

**Comment by pafi-code** [comment]
Okay thanks for clarification. I didn't know about the `outputs` subpackage for public interface. Thanks a lot and looking forward! :)

**Comment by pafi-code** [comment]
@dirkkul When will this be released ? 👉👈

**Comment by dirkkul** [comment]
End of this week probably
