### ISSUE TITLE
Should log import errors when using `batch.add_object`

### ISSUE THREAD

**Issue by netapy** [weaviate/weaviate-python-client#885]
I spent a while importing millions of objects into weaviate with `batch.add_object`, without any errors.
Problem is all of my properties didn't conform to the right datatypes (my mistake).

I would've loved for the Weaviate Client to at least print the import errors, it would have saved me a lot of time knowing it was all loading for nothing.

Thanks!

**Comment by dirkkul** [comment]
you can do

```
with collection.batch.dynamic() as batch
    ... do your things...
    if batch.number_errors > 10: # what ever number you like
         break

print(batch.failed_objects)
```

**Comment by netapy** [comment]
@dirkkul that's much clearer thanks. Didn't know it was included in the lib.

**Comment by dirkkul** [comment]
you're welcome! We are still working on the docs and are continously expanding them :)
