### ISSUE TITLE
Support ~ to negate nested filters

### ISSUE THREAD

**Issue by hsm207** [weaviate/weaviate-python-client#910]
Suppose we have this nested filter:

```
(wvc.query.Filter.by_property("points").greater_than(700) | wvc.query.Filter.by_property("points").less_than(300))
```

the negation is:

```
(wvc.query.Filter.by_property("points").less_or_equal(700) & wvc.query.Filter.by_property("points").greater_or_equal(300))
```

it would be convenient if users can just take the first expression and apply the ~ operator to negate it:

```
~(wvc.query.Filter.by_property("points").greater_than(700) | wvc.query.Filter.by_property("points").less_than(300))

```

**Comment by dirkkul** [comment]
sounds nice, but I think there are too many cases where we cannot automatically negate things, at least until we have a NOT operator in weaviate again

Just some example:
- like
- contains_any
- geo-coordinates

closing for now as this is currently out of scope
