### ISSUE TITLE
Long-running issue for docstring improvements

### ISSUE THREAD

**Issue by tsmith023** [weaviate/weaviate-python-client#918]
Currently, many of the docstrings are inaccurate in their description of poorly formatted with respect to the IDE and readthedocs.org rendering styles. This issue serves as a central location to log all the problems and to then tick them off as and when they are addressed.

- [ ]  Ensure that `WeaviateGRPCQueryError` is replaced with `WeaviateQueryError` everywhere it appears in docstrings

**Comment by dirkkul** [comment]
I think this is done - lets just do one item per issue then it is easier to close things :)
