### ISSUE TITLE
Make collections/filters support empty lists

### ISSUE THREAD

**Issue by MichaelOwenDyer** [weaviate/weaviate-python-client#929]
I would like to be able to do this:
```python
filter = wvc.query.Filter.by_property("degree_programs").equal([])
if degrees:
    filter = filter | wvc.query.Filter.by_property("degree_programs").contains_any(val=degrees)
```
to query chunks with no elements in the "degree_programs" property (general documents) and, optionally, chunks about one of the specified degree programs. However, the first part of this filter causes an error:
```
  File "/Users/michael/PycharmProjects/TUM_MGT_Chatbot/.venv/lib/python3.12/site-packages/weaviate/collections/filters.py", line 141, in __filter_to_int_list
    if not isinstance(value, list) or not isinstance(value[0], int):
                                                     ~~~~~^^^
IndexError: list index out of range
```
It seems that `weaviate/collections/filters.py` assumes (in several places) that any filter list will be non-empty. In my opinion this is not a reasonable assumption.

**Comment by tsmith023** [comment]
Hi Michael, this should be fixed by the latest `4.5.1` release. LMK if it doesn't otherwise I will close this issue 😁

**Comment by MichaelOwenDyer** [comment]
Oh I see. That's very helpful, thank you!

**Comment by tsmith023** [comment]
No problem! I think we can improve the error handling for an empty list here rather than having an index out of range error so I will open an issue to cover that
