### ISSUE TITLE
Improve typing of filters

### ISSUE THREAD

**Issue by dirkkul** [weaviate/weaviate-python-client#936]
Currently we return _FilterValue, _FilterAnd and _FilterOr from various filter functions. This makes it a type error when using `&=`and `|=` which works without problems. Instead all of these functions should return _Filters (which is the baseclass for all the other Filtertypes). The exact subtype is only relevant internally and not for users as all of them can be freely combined

**Comment by tsmith023** [comment]
Implemented in https://github.com/weaviate/weaviate-python-client/pull/973
