### ISSUE TITLE
Can't use hybrid search within an aggregate query

### ISSUE THREAD

**Issue by touatiosema** [weaviate/weaviate-python-client#939]
### Adding the hybrid search field is not possible when aggregating  

Hybrid search is not supported when trying to build an aggregate query using `AggregateBuilder` class, in graphql console, the following query is possible:
```graphql
{
  Aggregate {
    Employees(
      hybrid: {
        query: "africa"
        alpha: 0
      }
    	
    ){
      department{
        count type topOccurrences{ occurs value }
      }
    }
  }
}
```

The concerned class is: [Aggregate builder](https://github.com/weaviate/weaviate-python-client/blob/10b6a5bc6a4391e1831df36110e6ecafcf2d8bc1/weaviate/gql/aggregate.py#L1112), this builder doesn't seem to support adding the hybrid search field when aggregating.

Suggestion: add a `with_hybrid` method to allow the client to add the necessary hybrid headers.

**Comment by dirkkul** [comment]
this is added for v4
