### ISSUE TITLE
Create, remove and update tenants to accept both single items and lists

### ISSUE THREAD

**Issue by sebawita** [weaviate/weaviate-python-client#944]
Currently, the create, update, and remove tenant functions require us to provide a list of Tenant objects, even if we are dealing with one tenant object.

It would be nice, to have an option to either provide a single tenant object (without wrapping it in a list) or a list (the current behaviour).

```
papers.tenants.create(
    Tenant(name="ten-name")
)
```

```
papers.tenants.update(
    Tenant(name="ten-name", activity_status=TenantActivityStatus.HOT)
)
```

```
papers.tenants.remove("ten-name")
```

**Comment by tsmith023** [comment]
Implemented in https://github.com/weaviate/weaviate-python-client/pull/973
