### ISSUE TITLE
Create tenant by passing the name string

### ISSUE THREAD

**Issue by sebawita** [weaviate/weaviate-python-client#945]
It would be nice if we could shorten the code required to create a tenant.
Like this:

```
papers.tenants.create("ten-name")
```

```
papers.tenants.create([
  "ten-name",
  "nine-name"
])
```

**Comment by byronvoorbach** [comment]
We have implicit tenant creation on the backlog as well, where you don't have to create tenants up-front

**Comment by tsmith023** [comment]
Implemented in https://github.com/weaviate/weaviate-python-client/pull/973
