### ISSUE TITLE
Extend backup and restore creators to include configuration 

### ISSUE THREAD

**Issue by moogacs** [weaviate/weaviate-python-client#946]
the backup and restore endpoints now offers compression configuration to be adjusted by the endpoints like `Compression level`, `CPU percentage`, `Chunk size`

see new spec. 
- [BackupConfig](https://github.com/weaviate/weaviate/blob/master/openapi-specs/schema.json#L907)
- [RestoreConfig](https://github.com/weaviate/weaviate/blob/master/openapi-specs/schema.json#L940)

would like to extend the client to make that config available from the client side, so that users would be able to configure their backup and restore 

linked to https://github.com/weaviate/weaviate-go-client/issues/208

**Comment by tsmith023** [comment]
Implemented in https://github.com/weaviate/weaviate-python-client/pull/973
