### ISSUE TITLE
broadcast_abort_transaction: broadcast tx abort failed

### ISSUE THREAD

**Issue by arverma** [weaviate/weaviate-python-client#956]
### Context
This happens while updating a collection. My weaviate instance is running on GKE and this is the 1st time I encountered the issue since last 15 days. I have two collections(Benchmark and Benchmark_test). 

```
import weaviate
import weaviate.classes as wvc

client = weaviate.connect_to_custom(
    http_host="*.*.*.*",
    http_port=80,
    http_secure=False,
    grpc_host="*.*.*.*",
    grpc_port=50051,
    grpc_secure=False,
    )
articles = client.collections.get("Benchmark")

articles.aggregate.over_all(total_count=True)
# AggregateReturn(properties={}, total_count=11172946)

# articles = client.collections.get("Benchmark_test")
# articles.aggregate.over_all(total_count=True)
# AggregateReturn(properties={}, total_count=141195)
```

#### Update the collection
```
articles.config.update(
    replication_config=wvc.config.Reconfigure.replication(
        factor=2
    )
)
```
OR
```
articles.config.update(
    vector_index_config=wvc.config.Reconfigure.VectorIndex.hnsw(ef=256)
)
```
#### ERROR
```
{
action: "broadcast_abort_transaction"
error: "host "*.*.*.*:7001": send http request: Delete "http://*.*.*.*:7001/schema/transactions/ba832d25-3213-2322-13ds-3cefa2ewewc15": context deadline exceeded"
id: "ba832d25-3213-2322-13ds-3cefa2ewewc15"
level: "error"
msg: "broadcast tx abort failed"
}
```

**Query is working fine but Ingestion also seems to have some issue. I see this messages in the log for all the props.**
```
benchmark-ann-modified  | {'error': [{'message': "update inverted indices: put inverted indices props: no bucket for prop '**content**' found"}]}
```

Also tried:
`additional_config = weaviate.config.AdditionalConfig(timeout=(300, 600))`

The issue started flashing after I fired both the update command (replication_config and vector_index_config) in parallel. Did it lock something internally? 

Looking forward getting help in understanding where did it get wrong and how can I fix it.

**Comment by dirkkul** [comment]
Hi, this looks like a weaviate and not a client problem. I'd recommend to make a post in our support forum (https://forum.weaviate.io/)
