### ISSUE TITLE
Add `Explore` filter to `GraphQL` filters

### ISSUE THREAD

**Issue by StefanBogdan** [weaviate/weaviate-python-client#96]

**Comment by trengrj** [comment]
It would be very useful to have Explore. It also might be useful to have a helper for generating beacons like the below pseudo-code:

```python
from weaviate import Client, Beacon

client = Client("http://localhost:8080")

client.query.explore(Beacon("Class", "xxxx-xxx-xxx-xxx"))

client.query.get("Class", ["title"]) \
  .with_near_object(beacon=Beacon("Post", "xxxx-xxx-xxx-xxx"))

**Comment by StefanBogdan** [comment]
Hi @trengrj , there is a method to create beacons in the weaviate-client: https://weaviate-python-client.readthedocs.io/en/latest/weaviate.util.html#weaviate.util.generate_local_beacon

I like your approach more, so maybe we can add it in the next Major release.

Explore is not currently included as a different query attribute, but it is going to be part of the `v4.0.0`: https://github.com/semi-technologies/weaviate-python-client/blob/v4.0.0/weaviate/base/gql/explore.py
